### ISSUE TITLE
Linux progress status

### ISSUE THREAD

**Issue by Xottab-DUTY** [OpenXRay/xray-16#704]
Current Linux port step:
- [x] ~~_Project is not compileable_~~
- [x] ~~_Project is compileable but doesn't run_~~
- [x] ~~_Project runs, but doesn't work properly_~~
- [x] ~~_Alpha_~~
- [x]  ~~_Beta_~~
- [x] **Release**

Libraries unbundling status:
- [x] LuaBind (Use custom version for initial port)
- [x] LuaJit [#33](https://github.com/OpenXRay/xray-16/issues/33)
- [x] ~~TinyXML~~ refused to unbundle
- [x] ODE [#44](https://github.com/OpenXRay/xray-16/issues/44) (Use custom version for initial port)
- [x] OpenAL [#45](https://github.com/OpenXRay/xray-16/issues/45)(Now use system library, probably not needed)
- [ ] GameSpy [#46](https://github.com/OpenXRay/xray-16/issues/46) (can be disabled for Linux?)
- [x] Lzo [#47](https://github.com/OpenXRay/xray-16/issues/47)
- [ ] PPM [#48](https://github.com/OpenXRay/xray-16/issues/48)

Linux port status:
- [x] Use CMake as build system [#21](https://github.com/OpenXRay/xray-16/issues/21)
  - [x] Linux build
    - [x] Fix Cryptopp usage
- [ ] Deal with mangled name of loadable procedures (make them pure C functions?) [example](https://github.com/Kaffeine/xray-16/blob/dev/src/xrScriptEngine/script_engine.cpp#L828)
- [x] Remove dll suffix from module names [#78](https://github.com/OpenXRay/xray-16/issues/78)
- [x] Port command line arguments processing from win32 GetCommandLine() to main(argc,argv).
- [x] xrCore
  - [X] Locator
    - [X] Fix everything being lowered
    - [X] Decide on forward <-> backward slashes. Note, that game resources also have paths.
    - [x] Introduce DirectoryLookup API
    - [x] Implement the API for posix.
  - [x] VFS
    - [x] Files mapping
  - [x] xrIni
  - [x] Introduce module lookup abstraction
    - [x] ~~Add XRay:: LoadLibrary/UnloadLibrary/GetProcAddress methods~~ (Replaced by XRay::Module)
    - [x] Add XRay::Module class to automatically load and unload modules
  - [x] Memory 
    - [x] Alloc/Free (Now we are using crossplatform TBB)
    - [x] Pool
    - [x] Usage info
  - [x] CPU
    - [x] Detection (via SDL2)
    - [x] Math
  - [x] Debug
    - [x] Log
    - [x] xrDebug
    - [x] StackTrace (optional, not required for the initial port)
  - [x] Strings
    - [x] xrString
    - [x] xrTrims
  - [x] Animation
  - [x] Containers
  - [x] Crypto
  - [x] Media
  - [x] PostProcess
  - [x] Text
  - [x] Threading
    - [x] Lock
    - [x] Event
    - [x] Trivial Threads API
  - [x] LZO Wrapper
  - [x] PPMd (done, except custom locks. Probably can be ported to xrCore/Threading/Lock)
  - [x] xrXMLParser (Should be easy enough)
- [x] xrEngine (see [src/xrEngine/CMakeLists.txt](https://github.com/Kaffeine/xray-16/blob/linux/src/xrEngine/CMakeLists.txt) for per-file build status)
  - [x] SDL backend for Input system
  - [x] SDL backend for Window system
- [x] xr_3da (Actual executable file)
- [x] xrRender
  - [x] Implement OpenGL backend
  - [x] Replace D3dUtils by glm (https://glm.g-truc.net)
- [x] xrAICore
- [x] xrCDB
- [x] xrGame
- [x] xrGameSpy
- [x] xrNetServer
  - [ ] Replace outdated DirectPlay
- [x] xrParticles
- [x] xrPhysics
- [x] xrScriptEngine
- [x] xrSound (OpenAL soft seems to fit all requirements, but we need to make EAX an optional dependency [#83](https://github.com/OpenXRay/xray-16/issues/83)

**Comment by Xottab-DUTY** [comment]
This issue previously was presented as a page on the project's wiki. After the project reached it's Beta stage, the page was almost abandoned and there's no much sense in it. Hence, I will close this issue immediately and just leave this page here for history.
