### ISSUE TITLE
GameSpy multimaster todo's

### ISSUE THREAD

**Issue by Xottab-DUTY** [OpenXRay/xray-16#710]
GameSpy multimaster (#519):
- [ ] By default, only show servers from one master server, depending on the game. (COP/CS/SOC)
  - [ ] Switch which servers to display using console command with three modes:
    1. Only show our game mode servers. (if we are in COP mode, show only servers from COP master-server)
    2. Show our game mode servers and available versions, even if they are not from our game mode. (same as first, but if we are in COP mode and have CS 1.5.10 installed, show CS 1.5.10 servers too)
    3. Show all server from all master-servers.
  - [ ] Add ability to hide servers with version different from our version. (console command, off by default)
- [x] ~~Server list UI should use game version switcher: if our version is 1.6.03 and we also have 1.6.02 installed, then run 1.6.02 version when user tries to connect.~~ Version switcher was removed.

~~Game version switcher (#491):~~ Removed.
- [x] ~~Add ability to specify working directory in verdesc.ltx~~
- [x] ~~Filesystem ability to recognize files from specific version directory as files from root directory:~~
  - ~~stalker/versions/ver/gamedata -> stalker/gamedata~~

**Comment by QuaiGoner** [comment]
Is there a guide on how to use game swithcer feature since PR is merged?

**Comment by Xottab-DUTY** [comment]
> By default, only show servers from one master server, depending on the game. (COP/CS/SOC)

> Switch which servers to display using console command with three modes

These ideas are abandoned. Not really needed.

That means that there are no more multimaster TODOs and this issue is closes.
